eureka:
  instance:
    hostname: localhost
  client:
    server-url:
      default-zoneone: http://localhost:8761/eureka/
server:
  port: 8070
spring:
  application:
    name: mf-core
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
