eureka:
  instance:
    hostname: localhost
  client:
    server-url:
      default-zoneone: http://localhost:8761/eureka/
server:
  port: 8069
spring:
  application:
    name: mf-core
  config:
    import: optional:configserver:http://localhost:8888
