eureka:
  instance:
    hostname: localhost
  client:
    server-url:
      default-zoneone: http://localhost:8761/eureka/
server:
  port: 8069
spring:
  application:
    name: mf-core
  config:
    import: optional:configserver:http://localhost:8888

application:
  config:
    mf-transactions-url: http://localhost:8071/api/v1/transactions
    mf-users-url: http://localhost:8070/api/v1/user
